[theme]
base = "light"
primaryColor = "#d97706"
backgroundColor = "#f5f5f4"
secondaryBackgroundColor = "#ffffff"
textColor = "#292524"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
